steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_IMAGE}
      - .

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_IMAGE}
      - --region
      - ${_REGION}
      - --platform
      - managed
      - --allow-unauthenticated
      - --set-env-vars
      - GROQ_CLOUD_API=${_GROQ_CLOUD_API}

images:
  - ${_IMAGE}

substitutions:
  _SERVICE: hackfest-backend
  _REGION: us-central1
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/hackfest/backend:latest
  _GROQ_CLOUD_API: ""

